#
# Copyright (C) 2013 Broadcom Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

obj-y := common.o gisb.o
obj-$(CONFIG_SMP) += headsmp.o hotplug.o platsmp.o
obj-$(CONFIG_CMA) += cma_driver.o
obj-$(CONFIG_PM) += s2.o pm.o
